language: ruby
rvm:
- 2.3.3

before_install:
  - sudo add-apt-repository ppa:duggan/bats -y
  - sudo apt-get -qq update
  - sudo apt-get install -y bats
  - sudo apt-get install -y libxml2-utils

script: ./test.sh

sudo: required
